const CONFIG = { ADA_USD: 0.44, PRN_ADA: 2.2 };
const ASSETS = [
    { id: 'prn', symbol: 'PRN', logo: 'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/coins/prn_coin.png', balance: 2540.00 },
    { id: 'ada', symbol: 'ADA', logo: 'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/coins/ada_coin.png', balance: 38.00 },
    { id: 'nrl', symbol: 'NRL', logo: 'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/logos/neural_coin_hf.png', balance: 0.00 },
    { id: 'musd', symbol: 'MUSD', logo: 'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/coins/musd_coin.png', balance: 0.00 }
];
let WALLETS = [{ name: 'Architect', handle: '$prisca.pri', pfp: 'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/p-logo.png' }];

function initializeWallet(c) {
    const d = document.getElementById(c); if(!d) return;
    d.innerHTML = '<div id="w-root" style="height:100%;width:100%;background:#000;color:white;font-family:sans-serif;overflow:hidden;"></div>';
    if(!sessionStorage.getItem('prn_unlocked')) renderSplash(); else renderAssets();
}
function renderSplash() {
    const r = document.getElementById('w-root'); if(!r) return;
    r.innerHTML = '<div style="height:100%;display:flex;flex-direction:column;justify-content:center;align-items:center;"><img src="https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/logos/p-logo.png" style="width:80px;animation:pulse 2s infinite alternate;"></div>';
    setTimeout(renderAssets, 1500);
}
function renderAssets() {
    sessionStorage.setItem('prn_unlocked','true');
    const r = document.getElementById('w-root'); if(!r) return;
    r.innerHTML = '<div style="padding:25px;height:100%;display:flex;flex-direction:column;"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;"><div style="display:flex;align-items:center;gap:12px;cursor:pointer;" onclick="renderProfile()"><img src="'+WALLETS[0].pfp+'" style="width:35px;height:35px;border-radius:50%;border:1.5px solid #7B35D4;"><div><div style="font-weight:900;font-size:0.7rem;">'+WALLETS[0].name+'</div><div style="color:#7B35D4;font-size:0.6rem;font-weight:900;">'+WALLETS[0].handle+' ▼</div></div></div><div style="display:flex;gap:15px;"><button style="background:none;border:none;color:#444;font-size:1.2rem;cursor:pointer;">⚙️</button><button onclick="toggleSidebar()" style="background:none;border:none;color:#555;font-size:1.5rem;cursor:pointer;">✕</button></div></div><div style="background:linear-gradient(135deg,#7B35D4,#3b0764);padding:25px;border-radius:30px;margin-bottom:20px;"><div style="font-size:0.6rem;opacity:0.7;letter-spacing:1px;font-weight:800;">PORTFOLIO VALUE</div><div style="font-size:2rem;font-weight:900;margin:10px 0;">$16.72</div><div style="display:flex;gap:10px;margin-top:15px;"><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;">SEND</button><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;">RECEIVE</button><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;">SWAP</button></div></div><div style="flex:1;overflow-y:auto;">' + ASSETS.map(a=>`<div style="display:flex;justify-content:space-between;padding:15px;background:#0A0A0A;border:1px solid #111;border-radius:20px;margin-bottom:10px;"><div style="display:flex;align-items:center;gap:10px;"><img src="${a.logo}" style="width:24px;border-radius:50%;"><div><div style="font-weight:900;font-size:0.8rem;">${a.symbol}</div></div></div><div style="font-weight:900;">${a.balance}</div></div>`).join('') + '</div><div style="display:flex;justify-content:space-around;background:#080808;padding:18px;border-radius:25px;border:1px solid #111;margin-top:auto;"><button onclick="renderAssets()" style="background:none;border:none;color:#7B35D4;font-size:1.5rem;cursor:pointer;">💰</button><button onclick="renderStake()" style="background:none;border:none;color:#333;font-size:1.5rem;cursor:pointer;">🥩</button><button onclick="renderChat()" style="background:none;border:none;color:#333;font-size:1.5rem;cursor:pointer;">💬</button><button onclick="renderVault()" style="background:none;border:none;color:#333;font-size:1.5rem;cursor:pointer;">🔒</button></div></div>';
}
function renderProfile() { document.getElementById('w-root').innerHTML = '<div style="padding:30px;text-align:center;"><h3>Profile</h3><img src="'+WALLETS[0].pfp+'" style="width:80px;border-radius:50%;border:2px solid #7B35D4;margin:20px 0;"><h4>'+WALLETS[0].name+'</h4><button style="background:#7B35D4;color:white;margin-top:20px;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;" onclick="renderAssets()">BACK</button></div>'; }
function renderStake() { document.getElementById('w-root').innerHTML = '<div style="padding:30px;text-align:center;"><h3>Staking</h3><p style="color:#666;">Yield engine offline.</p><button style="background:#7B35D4;color:white;margin-top:20px;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;" onclick="renderAssets()">BACK</button></div>'; }
function renderChat() { document.getElementById('w-root').innerHTML = '<div style="padding:30px;height:100%;display:flex;flex-direction:column;"><h3>Neural Bridge</h3><div style="flex:1;background:#050505;border:1px solid #111;border-radius:20px;padding:15px;margin-bottom:20px;font-size:0.7rem;color:#444;">Handshake active. Session encrypted.</div><button style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;" onclick="renderAssets()">BACK</button></div>'; }
function renderVault() { document.getElementById('w-root').innerHTML = '<div style="padding:30px;height:100%;display:flex;flex-direction:column;"><h3>Sovereign Vault</h3><div style="margin-top:20px;flex:1;"><div style="padding:15px;background:#0A0A0A;border-radius:15px;margin-bottom:10px;">📂 Birth_Cert.pri</div><div style="padding:15px;background:#0A0A0A;border-radius:15px;margin-bottom:10px;">📂 Deeds.pri</div><div style="padding:15px;background:#0A0A0A;border-radius:15px;margin-bottom:10px;">🏰 Manifest.pri</div></div><button style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;" onclick="renderAssets()">BACK</button></div>'; }
function toggleSidebar() { const s = document.getElementById("sidebar"); s.classList.toggle("active"); if(s.classList.contains("active")) initializeWallet("sidebar"); }
const st = document.createElement("style"); st.textContent = "@keyframes pulse-3d { from{transform:scale(1)} to{transform:scale(1.1)} }"; document.head.appendChild(st);
window.addEventListener("load", () => { if(document.getElementById("sidebar")) initializeWallet("sidebar"); });
