const CONFIG={ADA_USD:0.44,PRN_USD:0.198,PRN_ADA:2.22};
const ASSETS=[{id:'prn',symbol:'PRN',logo:'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/coins/prn_coin.png',balance:2540},{id:'ada',symbol:'ADA',logo:'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/coins/ada_coin.png',balance:38}];
let WALLETS=JSON.parse(localStorage.getItem('prn_wallets'))||[{name:'Architect',handle:'$prisca.pri',pfp:'https://raw.githubusercontent.com/priscadezigns9/priscadezignswebsite/main/assets/p-logo.png'}];
let CHAT=JSON.parse(localStorage.getItem('prn_chat'))||[{s:'JARVIS',t:'Neural Bridge Active.'}];

function initializeWallet(c){const d=document.getElementById(c);if(!d)return;d.innerHTML='<div id="w-root" style="height:100%;width:100%;background:#000;color:white;font-family:sans-serif;overflow:hidden;position:relative;"></div>';renderAssets();}
function renderAssets(){const r=document.getElementById('w-root');if(!r)return;const usd=(ASSETS[1].balance*0.44)+(ASSETS[0].balance*0.198);r.innerHTML='<div style="padding:25px;height:100%;display:flex;flex-direction:column;box-sizing:border-box;"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;"><div style="display:flex;align-items:center;gap:10px;cursor:pointer;" onclick="renderProfile()"><img src="'+WALLETS[0].pfp+'" style="width:35px;height:35px;border-radius:50%;border:1px solid #7B35D4;object-fit:cover;"><div><div style="font-weight:900;font-size:0.7rem;">'+WALLETS[0].name+'</div><div style="color:#7B35D4;font-size:0.5rem;font-weight:900;" onclick="event.stopPropagation();renderHandleMenu()">'+WALLETS[0].handle+' ▼</div></div></div><button onclick="toggleSidebar()" style="background:none;border:none;color:#555;font-size:1.5rem;cursor:pointer;">✕</button></div><div style="background:linear-gradient(135deg,#7B35D4,#3b0764);padding:25px;border-radius:30px;margin-bottom:20px;"><small>TOTAL EQUITY</small><div style="font-size:2rem;font-weight:900;margin:10px 0;">$'+usd.toFixed(2)+'</div><div style="display:flex;gap:8px;"><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;" onclick="renderSend()">SEND</button><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;" onclick="renderReceive()">RECEIVE</button><button style="flex:1;background:rgba(255,255,255,0.1);border:none;color:white;padding:10px;border-radius:12px;font-weight:900;font-size:0.6rem;" onclick="renderSwap()">SWAP</button></div></div><div style="flex:1;overflow-y:auto;padding-bottom:80px;">' + ASSETS.map(a=>`<div style="display:flex;justify-content:space-between;padding:15px;background:#0A0A0A;border:1px solid #111;border-radius:20px;margin-bottom:10px;"><div style="display:flex;align-items:center;gap:10px;"><img src="${a.logo}" style="width:24px;border-radius:50%;"><b>${a.symbol}</b></div><b>${a.balance}</b></div>`).join('') + '</div>'+renderNav('assets')+'</div>';}
function renderNav(a){const s={assets:'💰',stake:'🥩',chat:'💬',vault:'🔒'};return '<div style="display:flex;justify-content:space-around;background:#080808;padding:15px;border-radius:30px;border:1px solid #111;position:absolute;bottom:25px;left:25px;right:25px;z-index:100;">'+Object.keys(s).map(k=>`<button onclick="render${k.charAt(0).toUpperCase()+k.slice(1)}()" style="background:none;border:none;color:${a===k?'#7B35D4':'#333'};font-size:1.5rem;cursor:pointer;">${s[k]}</button>`).join('')+'</div>';}
function renderChat(){const r=document.getElementById('w-root');r.innerHTML='<div style="padding:25px;height:100%;display:flex;flex-direction:column;box-sizing:border-box;"><h3>Neural Bridge</h3><div id="chat-f" style="flex:1;background:#050505;border:1px solid #111;border-radius:25px;padding:15px;margin-bottom:20px;overflow-y:auto;">'+CHAT.map(m=>`<div style="text-align:${m.s==='Architect'?'right':'left'};margin-bottom:12px;"><div style="display:inline-block;background:${m.s==='Architect'?'#7B35D4':'#111'};padding:10px;border-radius:15px;font-size:0.8rem;max-width:85%;">`+m.t+`</div></div>`).join('')+'</div><div style="display:flex;gap:10px;margin-bottom:100px;align-items:center;"><label style="cursor:pointer;font-size:1.5rem;color:#444;">📎<input type="file" style="display:none" onchange="alert(\'File anchored.\')"></label><input id="ci" type="text" placeholder="Command..." style="flex:1;background:#0A0A0A;border:1px solid #111;padding:15px;border-radius:15px;color:white;outline:none;"><button onclick="sendC()" style="background:#7B35D4;border:none;width:50px;height:50px;border-radius:15px;color:white;">></button></div>'+renderNav('chat')+'</div>';const f=document.getElementById('chat-f');f.scrollTop=f.scrollHeight;}
function sendC(){const i=document.getElementById('ci');if(!i.value)return;CHAT.push({s:'Architect',t:i.value});localStorage.setItem('prn_chat',JSON.stringify(CHAT));renderChat();setTimeout(()=>{CHAT.push({s:'JARVIS',t:'Command registered.'});renderChat();},1000);}
function renderStake(){document.getElementById('w-root').innerHTML='<div style="padding:25px;height:100%;display:flex;flex-direction:column;box-sizing:border-box;"><h3>Yield Engine</h3><div style="background:#0A0A0A;padding:20px;border-radius:24px;border:1px solid #111;margin-bottom:15px;">PRN Staking: <b style="color:#00FF88">4.5%</b></div><div style="background:#0A0A0A;padding:20px;border-radius:24px;border:1px solid #111;">PRN/ADA LP: <b style="color:#00FF88">12.8%</b></div>'+renderNav('stake')+'</div>';}
function renderVault(){const n=[{n:"Birth_Cert.pri",i:"🖼️"},{n:"Deeds.pri",i:"🏠"}];document.getElementById('w-root').innerHTML='<div style="padding:25px;height:100%;display:flex;flex-direction:column;box-sizing:border-box;"><h3>Vault</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;flex:1;">'+n.map(x=>`<div style="background:#0A0A0A;padding:15px;border-radius:20px;text-align:center;border:1px solid #111;cursor:pointer;"><div style="font-size:2rem">${x.i}</div><div style="font-size:0.6rem;font-weight:900;">${x.n}</div></div>`).join('')+'</div>'+renderNav('vault')+'</div>';}
function renderProfile(){document.getElementById('w-root').innerHTML='<div style="padding:40px;text-align:center;"><h3>Profile</h3><img src="'+WALLETS[0].pfp+'" style="width:100px;height:100px;border-radius:50%;border:2px solid #7B35D4;margin:20px 0;object-fit:cover;" onclick="p=prompt(\'URL\');if(p){WALLETS[0].pfp=p;localStorage.setItem(\'prn_wallets\',JSON.stringify(WALLETS));renderProfile()}"><h4>'+WALLETS[0].name+'</h4><button onclick="renderAssets()" style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;margin-top:20px;cursor:pointer;">BACK</button></div>';}
function renderReceive(){document.getElementById('w-root').innerHTML='<div style="padding:30px;text-align:center;"><h3>Receive</h3><div style="background:#fff;padding:15px;display:inline-block;border-radius:20px;"><img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=addr1q8...prisca"></div><button onclick="renderAssets()" style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;margin-top:20px;cursor:pointer;">BACK</button></div>';}
function renderSend(){document.getElementById('w-root').innerHTML='<div style="padding:30px;"><h3>Send</h3><input type="text" placeholder="Handle" style="width:100%;background:#0A0A0A;border:1px solid #111;padding:15px;border-radius:15px;color:white;margin:20px 0;"><button onclick="renderAssets()" style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;cursor:pointer;">CONTINUE</button></div>';}
function renderSwap(){document.getElementById('w-root').innerHTML='<div style="padding:30px;"><h3>Swap</h3><div style="background:#0A0A0A;padding:20px;border-radius:20px;border:1px solid #111;margin-top:20px;"><small>FROM ADA</small></div><div style="text-align:center;padding:10px;">↓</div><div style="background:#0A0A0A;padding:20px;border-radius:20px;border:1px solid #111;"><small>TO PRN</small></div><button onclick="renderAssets()" style="background:#7B35D4;color:white;padding:15px;width:100%;border-radius:15px;border:none;font-weight:900;margin-top:30px;cursor:pointer;">SWAP</button></div>';}
function renderHandleMenu(){document.getElementById('w-root').innerHTML='<div style="padding:30px;"><h3>Node</h3><button style="width:100%;background:#111;color:white;padding:15px;border-radius:15px;border:none;font-weight:900;margin-bottom:10px;cursor:pointer;">+ CREATE</button><button onclick="renderAssets()" style="width:100%;background:#7B35D4;color:white;padding:15px;border-radius:15px;border:none;font-weight:900;margin-top:30px;cursor:pointer;">BACK</button></div>';}
function triggerPurchase(s,u,p,a){ toggleSidebar(); setTimeout(()=>alert(\'Checkout: \'+s), 500); }
function toggleSidebar(){const s=document.getElementById("sidebar");if(!s)return;s.classList.toggle("active");if(s.classList.contains("active"))initializeWallet("sidebar");}
const st=document.createElement("style");st.textContent=".sidebar{position:fixed;right:-420px;top:0;width:400px;height:100vh;background:#000;transition:0.5s;z-index:10000;border-left:1px solid #111}.sidebar.active{right:0}";document.head.appendChild(st);
window.addEventListener("load",()=>{if(document.getElementById("sidebar"))initializeWallet("sidebar");});
