name: Final Combine
on:
  push:
    paths:
      - 'index_chunk_*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Combine Chunks
      run: |
        cat index_chunk_aa.html index_chunk_ab.html index_chunk_ac.html index_chunk_ad.html index_chunk_ae.html index_chunk_af.html index_chunk_ag.html index_chunk_ah.html index_chunk_ai.html index_chunk_aj.html > index.html
        git config --global user.email 'priscillanarine@gmail.com'
        git config --global user.name 'Prisca Dezigns'
        git add index.html
        git commit -m 'Evolve to AI Automation Workforce [skip ci]'
        git push
